# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\cholen\.qgis2\python\plugins\EMT\Ui_AddFire.ui'
#
# Created: Fri Dec 22 11:37:55 2017
#      by: PyQt4 UI code generator 4.10.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_AddFire(object):
    def setupUi(self, AddFire):
        AddFire.setObjectName(_fromUtf8("AddFire"))
        AddFire.resize(758, 465)
        self.reqGroupBox = QtGui.QGroupBox(AddFire)
        self.reqGroupBox.setGeometry(QtCore.QRect(30, 20, 341, 361))
        self.reqGroupBox.setObjectName(_fromUtf8("reqGroupBox"))
        self.stateLabel = QtGui.QLabel(self.reqGroupBox)
        self.stateLabel.setGeometry(QtCore.QRect(20, 30, 53, 16))
        self.stateLabel.setObjectName(_fromUtf8("stateLabel"))
        self.stateBox = QtGui.QComboBox(self.reqGroupBox)
        self.stateBox.setGeometry(QtCore.QRect(140, 30, 141, 22))
        self.stateBox.setObjectName(_fromUtf8("stateBox"))
        self.latLabel = QtGui.QLabel(self.reqGroupBox)
        self.latLabel.setGeometry(QtCore.QRect(20, 70, 53, 16))
        self.latLabel.setObjectName(_fromUtf8("latLabel"))
        self.longLabel = QtGui.QLabel(self.reqGroupBox)
        self.longLabel.setGeometry(QtCore.QRect(20, 110, 61, 16))
        self.longLabel.setObjectName(_fromUtf8("longLabel"))
        self.igDateLabel = QtGui.QLabel(self.reqGroupBox)
        self.igDateLabel.setGeometry(QtCore.QRect(20, 150, 81, 16))
        self.igDateLabel.setObjectName(_fromUtf8("igDateLabel"))
        self.evtTypeLabel = QtGui.QLabel(self.reqGroupBox)
        self.evtTypeLabel.setGeometry(QtCore.QRect(20, 190, 81, 16))
        self.evtTypeLabel.setObjectName(_fromUtf8("evtTypeLabel"))
        self.eventBox = QtGui.QComboBox(self.reqGroupBox)
        self.eventBox.setGeometry(QtCore.QRect(140, 190, 141, 22))
        self.eventBox.setObjectName(_fromUtf8("eventBox"))
        self.acreLabel = QtGui.QLabel(self.reqGroupBox)
        self.acreLabel.setGeometry(QtCore.QRect(20, 230, 53, 16))
        self.acreLabel.setObjectName(_fromUtf8("acreLabel"))
        self.pathLabel = QtGui.QLabel(self.reqGroupBox)
        self.pathLabel.setGeometry(QtCore.QRect(20, 270, 53, 16))
        self.pathLabel.setObjectName(_fromUtf8("pathLabel"))
        self.rowLabel = QtGui.QLabel(self.reqGroupBox)
        self.rowLabel.setGeometry(QtCore.QRect(20, 310, 53, 16))
        self.rowLabel.setObjectName(_fromUtf8("rowLabel"))
        self.igDateEdit = QtGui.QDateEdit(self.reqGroupBox)
        self.igDateEdit.setGeometry(QtCore.QRect(140, 150, 141, 22))
        self.igDateEdit.setObjectName(_fromUtf8("igDateEdit"))
        self.latSpinBox = QtGui.QDoubleSpinBox(self.reqGroupBox)
        self.latSpinBox.setGeometry(QtCore.QRect(140, 70, 141, 22))
        self.latSpinBox.setDecimals(3)
        self.latSpinBox.setMinimum(-80.0)
        self.latSpinBox.setMaximum(80.0)
        self.latSpinBox.setSingleStep(1.0)
        self.latSpinBox.setProperty("value", 0.0)
        self.latSpinBox.setObjectName(_fromUtf8("latSpinBox"))
        self.longSpinBox = QtGui.QDoubleSpinBox(self.reqGroupBox)
        self.longSpinBox.setGeometry(QtCore.QRect(140, 110, 141, 22))
        self.longSpinBox.setDecimals(3)
        self.longSpinBox.setMinimum(-180.0)
        self.longSpinBox.setMaximum(180.0)
        self.longSpinBox.setObjectName(_fromUtf8("longSpinBox"))
        self.pathSpinBox = QtGui.QSpinBox(self.reqGroupBox)
        self.pathSpinBox.setGeometry(QtCore.QRect(140, 270, 141, 22))
        self.pathSpinBox.setMinimum(1)
        self.pathSpinBox.setMaximum(251)
        self.pathSpinBox.setObjectName(_fromUtf8("pathSpinBox"))
        self.rowSpinBox = QtGui.QSpinBox(self.reqGroupBox)
        self.rowSpinBox.setGeometry(QtCore.QRect(140, 310, 141, 22))
        self.rowSpinBox.setMinimum(1)
        self.rowSpinBox.setMaximum(122)
        self.rowSpinBox.setObjectName(_fromUtf8("rowSpinBox"))
        self.acreSpinBox = QtGui.QSpinBox(self.reqGroupBox)
        self.acreSpinBox.setGeometry(QtCore.QRect(140, 230, 141, 22))
        self.acreSpinBox.setMaximum(999999)
        self.acreSpinBox.setObjectName(_fromUtf8("acreSpinBox"))
        self.opGroupBox = QtGui.QGroupBox(AddFire)
        self.opGroupBox.setGeometry(QtCore.QRect(400, 20, 331, 361))
        self.opGroupBox.setObjectName(_fromUtf8("opGroupBox"))
        self.evtNameLabel = QtGui.QLabel(self.opGroupBox)
        self.evtNameLabel.setGeometry(QtCore.QRect(20, 30, 81, 16))
        self.evtNameLabel.setObjectName(_fromUtf8("evtNameLabel"))
        self.nameEdit = QtGui.QLineEdit(self.opGroupBox)
        self.nameEdit.setGeometry(QtCore.QRect(190, 30, 121, 22))
        self.nameEdit.setObjectName(_fromUtf8("nameEdit"))
        self.eContDateLabel = QtGui.QLabel(self.opGroupBox)
        self.eContDateLabel.setGeometry(QtCore.QRect(20, 70, 171, 16))
        self.eContDateLabel.setObjectName(_fromUtf8("eContDateLabel"))
        self.expectedDateEdit = QtGui.QLineEdit(self.opGroupBox)
        self.expectedDateEdit.setGeometry(QtCore.QRect(190, 70, 121, 22))
        self.expectedDateEdit.setObjectName(_fromUtf8("expectedDateEdit"))
        self.aContDateLabel = QtGui.QLabel(self.opGroupBox)
        self.aContDateLabel.setGeometry(QtCore.QRect(20, 110, 151, 16))
        self.aContDateLabel.setObjectName(_fromUtf8("aContDateLabel"))
        self.actualDateEdit = QtGui.QLineEdit(self.opGroupBox)
        self.actualDateEdit.setGeometry(QtCore.QRect(190, 110, 121, 22))
        self.actualDateEdit.setObjectName(_fromUtf8("actualDateEdit"))
        self.fuelLabel = QtGui.QLabel(self.opGroupBox)
        self.fuelLabel.setGeometry(QtCore.QRect(20, 190, 53, 16))
        self.fuelLabel.setObjectName(_fromUtf8("fuelLabel"))
        self.reportDateEdit = QtGui.QLineEdit(self.opGroupBox)
        self.reportDateEdit.setGeometry(QtCore.QRect(190, 150, 121, 22))
        self.reportDateEdit.setObjectName(_fromUtf8("reportDateEdit"))
        self.commentLabel = QtGui.QLabel(self.opGroupBox)
        self.commentLabel.setGeometry(QtCore.QRect(20, 230, 81, 16))
        self.commentLabel.setObjectName(_fromUtf8("commentLabel"))
        self.commentEdit = QtGui.QLineEdit(self.opGroupBox)
        self.commentEdit.setGeometry(QtCore.QRect(190, 230, 121, 22))
        self.commentEdit.setObjectName(_fromUtf8("commentEdit"))
        self.repDateLabel = QtGui.QLabel(self.opGroupBox)
        self.repDateLabel.setGeometry(QtCore.QRect(20, 150, 91, 16))
        self.repDateLabel.setObjectName(_fromUtf8("repDateLabel"))
        self.fuelsEdit = QtGui.QLineEdit(self.opGroupBox)
        self.fuelsEdit.setGeometry(QtCore.QRect(190, 190, 121, 22))
        self.fuelsEdit.setObjectName(_fromUtf8("fuelsEdit"))
        self.agencyLabel = QtGui.QLabel(self.opGroupBox)
        self.agencyLabel.setGeometry(QtCore.QRect(20, 270, 53, 16))
        self.agencyLabel.setObjectName(_fromUtf8("agencyLabel"))
        self.adminUnitLabel = QtGui.QLabel(self.opGroupBox)
        self.adminUnitLabel.setGeometry(QtCore.QRect(20, 310, 81, 16))
        self.adminUnitLabel.setObjectName(_fromUtf8("adminUnitLabel"))
        self.agencyEdit = QtGui.QLineEdit(self.opGroupBox)
        self.agencyEdit.setGeometry(QtCore.QRect(190, 270, 121, 22))
        self.agencyEdit.setObjectName(_fromUtf8("agencyEdit"))
        self.adminEdit = QtGui.QLineEdit(self.opGroupBox)
        self.adminEdit.setGeometry(QtCore.QRect(190, 310, 121, 22))
        self.adminEdit.setObjectName(_fromUtf8("adminEdit"))
        self.eventIDButton = QtGui.QPushButton(AddFire)
        self.eventIDButton.setGeometry(QtCore.QRect(220, 410, 121, 28))
        self.eventIDButton.setObjectName(_fromUtf8("eventIDButton"))
        self.cancelButton = QtGui.QPushButton(AddFire)
        self.cancelButton.setGeometry(QtCore.QRect(410, 410, 93, 28))
        self.cancelButton.setObjectName(_fromUtf8("cancelButton"))

        self.retranslateUi(AddFire)
        QtCore.QObject.connect(self.cancelButton, QtCore.SIGNAL(_fromUtf8("clicked()")), AddFire.close)
        QtCore.QObject.connect(self.eventIDButton, QtCore.SIGNAL(_fromUtf8("clicked()")), AddFire.close)
        QtCore.QMetaObject.connectSlotsByName(AddFire)

    def retranslateUi(self, AddFire):
        AddFire.setWindowTitle(_translate("AddFire", "Add Fire", None))
        self.reqGroupBox.setTitle(_translate("AddFire", "Required Fields", None))
        self.stateLabel.setText(_translate("AddFire", "State", None))
        self.latLabel.setText(_translate("AddFire", "Latitude", None))
        self.longLabel.setText(_translate("AddFire", "Longitude", None))
        self.igDateLabel.setText(_translate("AddFire", "Ignition Date", None))
        self.evtTypeLabel.setText(_translate("AddFire", "Event Type", None))
        self.acreLabel.setText(_translate("AddFire", "Acres", None))
        self.pathLabel.setText(_translate("AddFire", "Path", None))
        self.rowLabel.setText(_translate("AddFire", "Row", None))
        self.opGroupBox.setTitle(_translate("AddFire", "Optional Fields", None))
        self.evtNameLabel.setText(_translate("AddFire", "Event Name", None))
        self.eContDateLabel.setText(_translate("AddFire", "Expected Containment Date", None))
        self.aContDateLabel.setText(_translate("AddFire", "Actual Containment Date", None))
        self.fuelLabel.setText(_translate("AddFire", "Fuels", None))
        self.commentLabel.setText(_translate("AddFire", "Comment", None))
        self.repDateLabel.setText(_translate("AddFire", "Report Date", None))
        self.agencyLabel.setText(_translate("AddFire", "Agency", None))
        self.adminUnitLabel.setText(_translate("AddFire", "Admin Unit", None))
        self.eventIDButton.setText(_translate("AddFire", "Create Event ID", None))
        self.cancelButton.setText(_translate("AddFire", "Cancel", None))

